<a href="https://colab.research.google.com/github/jay-thakur/DataScienceTutorial/blob/main/Tensorflow/2_Constant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Constant in Tensor

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.6.0


# What is a constant in Tensorflow?

In TensorFlow, a constant is a special Tensor that cannot be modified while the graph is running.

# How to create a constant in Tensorflow ?
we can create a constant tensor from a tensor-like object using `tf.constant`.

Let's create constant.

## Creating a Scaler constant

In [ ]:
scalar = tf.constant(1)
print ("Scalar (1 entry):\n\n %s" % scalar)

Scalar (1 entry):

 tf.Tensor(1, shape=(), dtype=int32)


we can also define dtype like this -

In [ ]:
scalar = tf.constant(1, dtype=tf.float64)
print ("Scalar (1 entry):\n\n %s" % scalar)

Scalar (1 entry):

 tf.Tensor(1.0, shape=(), dtype=float64)


Here we can see constant value is float (`1.0`)

## Creating a Vector constant

In [ ]:
vector = tf.constant([1], name = 'vector_1')
print ("Vector (1 entries) :\n\n %s" % vector)

Vector (1 entries) :

 tf.Tensor([1], shape=(1,), dtype=int32)


In [ ]:
vector = tf.constant([1, 2, 3], name = 'vector_1')
print ("Vector (3 entries) :\n\n %s" % vector)

Vector (3 entries) :

 tf.Tensor([1 2 3], shape=(3,), dtype=int32)


As we can see, it just shows the value, shape and dtype of the tensor in the graph, We can get it's value as a Numpy array by calling `.numpy()`.

In [ ]:
tf.print(vector.numpy())

array([1, 2, 3], dtype=int32)


## Creating matrix tensor

In [ ]:
matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print ("Matrix (3x3 entries):\n\n %s" % matrix)

Matrix (3x3 entries):

 tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


# Creating a Tensor

In [ ]:
tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
print ("Tensor (3x3x3 entries) :\n\n %s" % tensor)

Tensor (3x3x3 entries) :

 tf.Tensor(
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]], shape=(3, 3, 3), dtype=int32)


# Tensor Attributes

like numpy, Tensor attributes are `shape` `dtype`

In [ ]:
print('Scaler shape : %s, dtype : %s \n' %(scalar.shape, scalar.dtype))
print('Vector shape : %s, dtype : %s \n' %(vector.shape, vector.dtype))
print('Matrix shape : %s, dtype : %s \n' %(matrix.shape, matrix.dtype))
print('Tensor shape : %s, dtype : %s \n' %(tensor.shape, tensor.dtype))

Scaler shape : (), dtype : <dtype: 'float64'> 

Vector shape : (3,), dtype : <dtype: 'int32'> 

Matrix shape : (3, 3), dtype : <dtype: 'int32'> 

Tensor shape : (3, 3, 3), dtype : <dtype: 'int32'> 



# Syntax of creating constant - 


`tf.constant(
    value, dtype=None, shape=None, name='Const'
)`

<a href="https://www.tensorflow.org/api_docs/python/tf/constant#args"> learn more</a>

* If the argument dtype is not specified, then the type is inferred from the type of value.

* If dtype is specified, the resulting tensor values are cast to the requested dtype.

* If shape is set, the value is reshaped to match. Scalars are expanded to fill the shape:


# Creating Zeros & Ones Tensor

we can create `zeros` & `ones` constant tensors using `tf.zeros` and `tf.ones` (just like `np.zeros` and `np.ones`):

#### Creating Zeros tensor

In [ ]:
print(tf.zeros(shape=(2, 2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


#### Creating Ones tensor

In [ ]:
print(tf.ones(shape=(2, 2)))

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


# Generating Random values

This is all pretty [normal](https://www.tensorflow.org/api_docs/python/tf/random/normal):

In [ ]:
normal_values = tf.random.normal(shape=(2, 2), mean=0., stddev=1.)
print('Random Values drawn from normal distribution :\n\n', normal_values)

Random Values drawn from normal distribution :

 tf.Tensor(
[[ 0.6263331   0.68845373]
 [ 1.0842736  -0.48697865]], shape=(2, 2), dtype=float32)


And here's an integer tensor with values drawn from a random [uniform](https://www.tensorflow.org/api_docs/python/tf/random/uniform) distribution:

In [ ]:
uniform_values = tf.random.uniform(shape=(2, 2), minval=0, maxval=10, dtype='int32')
print('Random Values drawn from uniform distribution :\n\n', uniform_values)

Random Values drawn from uniform distribution :

 tf.Tensor(
[[6 7]
 [8 9]], shape=(2, 2), dtype=int32)


# References

https://www.tensorflow.org/api_docs/python/tf/constant

https://www.easy-tensorflow.com/tf-tutorials/basics/tensor-types

https://github.com/SciSharp/TensorFlow.NET/blob/master/docs/source/Constant.md

https://github.com/farhadkamangar/CSE5368 

https://cognitiveclass.ai/courses/course-v1:BigDataUniversity+ML0120EN+v2
