<a href="https://colab.research.google.com/github/jay-thakur/DataScienceTutorial/blob/main/Tensorflow/4_BasicOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operations

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.6.0


Operations are nodes that perform the mathematical operations over the tensors on a graph. 

An operations takes zero or more Tensor(s) as input and produces zero or more Tensors as output.

Operations can be any kind of functions like add and subtract tensor or maybe an activation function.


# Basic Math Operations

#### Add

In [ ]:
a = tf.constant([5])
b = tf.constant([2])

In [ ]:
c = tf.add(a,b)
print ('c =: %s' % c)

#### Subtract

In [ ]:
d = tf.subtract(a,b)
print ('d =: %s' % d)

d =: tf.Tensor([3], shape=(1,), dtype=int32)


#### Multiply

In [ ]:
e = tf.multiply(a,b)
print ('e =: %s' % e)

e =: tf.Tensor([10], shape=(1,), dtype=int32)


#### Division

In [ ]:
f = tf.divide(a, b)
print ('f =: %s' % f)

f =: tf.Tensor([2.5], shape=(1,), dtype=float64)


#### Pow

In [ ]:
g = tf.pow(a, b)
print ('g =: %s' % g)

g =: tf.Tensor([25], shape=(1,), dtype=int32)


#### Sqrt

In [ ]:
tf.sqrt(a)

#### Exp

In [ ]:
tf.exp(a)

# Matrix Multiplication

In [ ]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])

product = tf.matmul(matrix1, matrix2)
print("Matrix multiplication:", product)

Matrix multiplication: tf.Tensor([[12.]], shape=(1, 1), dtype=float32)


# Assign Value

We can update the value of a Variable by using the methods `.assign(value)`, or `.assign_add(increment)` or `.assign_sub(decrement)`

In [ ]:
# crete a variable with value 0
var = tf.Variable(0)
print("Var is : \n", var)

# now assign var a new value 2
new_variable = tf.Variable(2)
var.assign(new_variable)
print("\nNew Var is : ", var)

Var is : 
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>

New Var is :  <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>


notice the var value is now `2`.

In [ ]:
# add a varible in the var & assign it
add_value = tf.Variable(5)
var.assign_add(add_value)
print("\n After adding the new Var is : ", var)

In [ ]:
# decrement var by new value & assign it
sub_value = tf.Variable(3)
var.assign_sub(sub_value)
print("\n After decrementing the new Var is : ", var)

In neural network, we can create mutable states (like weights, biases) using variables.

In [ ]:
# Let's create weight and update it with new weight value
w = tf.Variable(tf.random.normal(shape=(2, 2), mean=0., stddev=1.))

print('Weight : \n\n', w)

w_add = tf.Variable(tf.random.normal(shape=(2, 2), mean=0., stddev=1.))
print('\n Weight to be added : \n\n', w_add)

w.assign_add(w_add)
print('\n Updated Weight : \n\n', w)

# Casting

In [ ]:
a = tf.convert_to_tensor(2.)
b = tf.cast(a, tf.int32)
print(a)
print(b)

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(2, shape=(), dtype=int32)


# Shape

In [ ]:
a = tf.ones([2,3])
print(a.shape[0], a.shape[1]) # 2, 3
shape = tf.shape(a)           # a tensor
print(shape[0], shape[1])

2 3
tf.Tensor(2, shape=(), dtype=int32) tf.Tensor(3, shape=(), dtype=int32)


### Reshape
The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [ ]:
# creating a ones tensor of shape [1,2,3]
tensor1 = tf.ones([1,2,3])
print("\n Initial Tensor : \n\n ", tensor1)

# reshape tensor1 to shape [2,3,1]
tensor2 = tf.reshape(tensor1, [2,3,1]) 
print("\n After Reshaping : \n\n ", tensor2)

# reshape again
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
print("\n Again After Reshaping : \n\n ", tensor3)                                       


 Initial Tensor : 

  tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)

 After Reshaping : 

  tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)

 Again After Reshaping : 

  tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


The numer of elements in the reshaped tensor MUST match the number in the original.

###Slicing Tensors
We can use the slice operator on tensors to select specific axes or elements.

When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. Each subsequent value refrences a different dimension of the tensor.

Ex: ```tensor[dim1, dim2, dim3]```

In [ ]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)


# Better Performance with `tf.function`

We have learnt that, In TensorFlow 2, <a href='https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/eager.ipynb'>eager execution</a> is turned on by default. but this can come at the expense of performance and deployability.

We can use `tf.function` to make graphs out of your programs. It is a transformation tool that creates Python-independent dataflow graphs out of your Python code. This will help us create performant and portable models, and it is required to use SavedModel.

### Example

In [ ]:
a = tf.constant([2], name = 'constant_a')
b = tf.constant([3], name = 'constant_b')

Lets add 2 constants to our graph. 

Here calling `tf.constant([2], name = 'constant_a')` adds a single `tf.Operation` to the default graph. This operation produces the value 2, and returns a tf.Tensor that represents the value of the constant.

Similarly `b = tf.constant([3], name = 'constant_b')`.

Annotating the python functions with **tf.function** uses TensorFlow Autograph to create a TensorFlow **static execution graph** for the function.   tf.function annotation tells TensorFlow Autograph to transform function *add* into TensorFlow control flow, which then defines the TensorFlow static execution graph. this `static graph` improves the time.



In [ ]:
@tf.function
def add(a,b):
    c = tf.add(a, b)
    return c
result = add(a,b)

Even this silly example of adding 2 constants to reach a simple result defines the basis of TensorFlow. Likewise we can define out own operations (In this case our constants and *tf.add*) and decorate it with using the *tf.function* annotator.

# References

https://github.com/SciSharp/TensorFlow.NET/blob/master/docs/source/Operation.md

https://www.tensorflow.org/lite/guide/ops_compatibility

https://www.tensorflow.org/api_docs/python/tf/function

https://github.com/farhadkamangar/CSE5368 

https://cognitiveclass.ai/courses/course-v1:BigDataUniversity+ML0120EN+v2

